INPUT_DIR = ./inputs
LOG_DIR = ./checkpoints
RUN_DIR = ./mlruns
MAKEDATA_DIR = ./makedata

DATA1 = PPI
DATA1_DIR = $(INPUT_DIR)/${DATA1}
MAKEDATA1_PATH = $(MAKEDATA_DIR)/$(DATA1)/download.sh

DATA2 = DD
DATA2_DIR = $(INPUT_DIR)/${DATA2}
MAKEDATA2_PATH = $(MAKEDATA_DIR)/$(DATA2)/download.sh

DATA3 = MUTAG
DATA3_DIR = $(INPUT_DIR)/${DATA3}
MAKEDATA3_PATH = $(MAKEDATA_DIR)/$(DATA3)/download.sh

DATA4 = PROTEINS
DATA4_DIR = $(INPUT_DIR)/${DATA4}
MAKEDATA4_PATH = $(MAKEDATA_DIR)/$(DATA4)/download.sh

all: $(INPUT_DIR) $(LOG_DIR) $(RUN_DIR) $(DATA1_DIR) $(DATA2_DIR) $(DATA3_DIR) $(DATA4_DIR)

$(INPUT_DIR):
	mkdir -p $(INPUT_DIR)

$(LOG_DIR):
	mkdir -p $(LOG_DIR)

$(RUN_DIR):
	mkdir -p $(RUN_DIR)

$(DATA1_DIR): $(MAKEDATA1_PATH)
	sh $(MAKEDATA1_PATH)

$(DATA2_DIR): $(MAKEDATA2_PATH)
	sh $(MAKEDATA2_PATH)

$(DATA3_DIR): $(MAKEDATA3_PATH)
	sh $(MAKEDATA3_PATH)

$(DATA4_DIR): $(MAKEDATA4_PATH)
	sh $(MAKEDATA4_PATH)