python3 gnn/train.py \
    --gpu_ids -1 \
    --verbose \
    --loss_name mce \
    --network_name gcn \
    --dataset_name mutag \
    --train_transform_name indegree \
    --val_transform_name indegree \
    --optimizer_name adam \
    --n_epochs 10 \
    --data_dir ./inputs/MUTAG/ \
    --index_file_dir ./inputs/MUTAG/10fold_idx/ \
    --name gcn_mutag \
    --save_freq 5 \
    --save_dir ./checkpoints \
    --mlflow_root_dir ./mlruns/ \
    --run_name debug_gcn_mutag \
    --lr 1e-3 \
    --beta1 0.9 \
    --beta2 0.999
