python3 gnn/train.py \
    --gpu_ids -1 \
    --verbose \
    --loss_name bce \
    --network_name gcn \
    --dataset_name ppi \
    --train_transform_name indegree \
    --val_transform_name indegree \
    --optimizer_name adam \
    --n_epochs 10 \
    --data_dir ./inputs/PPI/ \
    --index_file_dir ./inputs/PPI/10fold_idx/ \
    --name gcn_ppi \
    --save_freq 5 \
    --save_dir ./checkpoints \
    --mlflow_root_dir ./mlruns/ \
    --run_name debug_gcn_ppi \
    --lr 1e-3 \
    --beta1 0.9 \
    --beta2 0.999
