python3 gnn/train.py \
    --gpu_ids 0 \
    --batch_size 64 \
    --verbose \
    --loss_name mce \
    --network_name gmlp_graph_classification \
    --dataset_name ptc_mr \
    --train_transform_name indegree \
    --val_transform_name indegree \
    --optimizer_name adam \
    --scheduler_name step \
    --n_epochs 50 \
    --data_dir ./inputs/PTC_MR/ \
    --name gmlp_ptc_mr_tuned \
    --save_freq 10 \
    --save_dir ./checkpoints \
    --mlflow_root_dir ./mlruns/ \
    --run_name ver1 \
    --lr 3.6e-4 \
    --beta1 0.9 \
    --beta2 0.9 \
    --hidden_dim 32 \
    --ffn_dim 64 \
    --n_layers 3 \
    --lr_decay_iters 300 \
    --lr_decay_gamma 0.3
