#!/bin/sh

#PJM -L rscgrp=regular-a
#PJM -L node=1
#PJM -L elapse=48:00:00
#PJM -g gs84
#PJM -j

module load cuda/11.1
module load pytorch/1.8.1

source /work/02/gs84/s84000/inductive_node_classification_models/.venv/bin/activate

# 1
# IMDB-BINARY
python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 2
# IMDB-BINARY
sleep 60 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 60 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 60 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 60 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 60 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 3
# IMDB-BINARY
sleep 120 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 120 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 120 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 120 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 120 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 4
# IMDB-BINARY
sleep 180 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 180 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 180 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 180 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 180 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 5
# IMDB-BINARY
sleep 240 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 240 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 240 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 240 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 240 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 6
# IMDB-BINARY
sleep 300 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 300 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 300 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 300 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 300 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 7
# IMDB-BINARY
sleep 360 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 360 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 360 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 360 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 360 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 8
# IMDB-BINARY
sleep 420 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 420 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 420 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 420 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 420 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 1
# IMDB-BINARY
sleep 480 && python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 480 && python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 480 && python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 480 && python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 480 && python3 gnn/tuning.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 2
# IMDB-BINARY
sleep 540 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 540 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 540 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 540 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 540 && python3 gnn/tuning.py --gpu_ids 1 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 3
# IMDB-BINARY
sleep 600 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 600 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 600 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 600 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 600 && python3 gnn/tuning.py --gpu_ids 2 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 4
# IMDB-BINARY
sleep 660 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 660 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 660 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 660 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 660 && python3 gnn/tuning.py --gpu_ids 3 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 5
# IMDB-BINARY
sleep 720 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 720 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 720 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 720 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 720 && python3 gnn/tuning.py --gpu_ids 4 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 6
# IMDB-BINARY
sleep 780 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 780 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 780 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 780 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 780 && python3 gnn/tuning.py --gpu_ids 5 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 7
# IMDB-BINARY
sleep 840 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 840 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 840 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 840 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 840 && python3 gnn/tuning.py --gpu_ids 6 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 8
# IMDB-BINARY
sleep 900 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-BINARY/ --name 1124_tuning_gmlp_graph_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# IMDB-MULTI
sleep 900 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name imdb_multi --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/IMDB-MULTI/ --name 1124_tuning_gmlp_graph_imdb_multi --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# MUTAG
sleep 900 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name mutag --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/MUTAG/ --name 1124_tuning_gmlp_graph_mutag --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
sleep 900 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PROTEINS/ --name 1124_tuning_gmlp_graph_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
sleep 900 && python3 gnn/tuning.py --gpu_ids 7 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 150 --data_dir ./inputs/PTC_MR/ --name 1124_tuning_gmlp_graph_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuning_1124 --lr 2.5e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 512 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

sleep 1200 && nvidia-smi &

wait