#!/bin/sh

#PJM -L rscgrp=regular-a
#PJM -L node=1
#PJM -L elapse=48:00:00
#PJM -g gs84
#PJM -j

module load cuda/11.1
module load pytorch/1.8.1

source /work/02/gs84/s84000/inductive_node_classification_models/.venv/bin/activate

# 0
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 1
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_1_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 2
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_2_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 3
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 4
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 5
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 6
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

# 7
# IMDB-BINARY
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 3.03e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 3.56e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 3 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 3.20e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 16 --ffn_dim 256 --n_layers 5 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 2.64e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name imdb_binary --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/IMDB-BINARY/ --name 1123_tuned_gmlp_graph_classification_imdb_binary --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_4 --lr 3.35e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 256 --n_layers 2 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PROTEINS
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 9.80e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 64 --ffn_dim 128 --n_layers 7 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 8.59e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 256 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 20 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_2 --lr 8.30e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 4 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name proteins --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PROTEINS/ --name 1123_tuned_gmlp_graph_classification_proteins --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_3 --lr 8.68e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 32 --ffn_dim 128 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &
# PTC_MR
python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 100 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_0 --lr 1.65e-3 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. \
    && python3 gnn/train.py --gpu_ids 0 --batch_size 2048 --verbose --loss_name mce --network_name gmlp_graph_classification --dataset_name ptc_mr --train_transform_name indegree --val_transform_name indegree --optimizer_name adam --scheduler_name step --n_epochs 50 --data_dir ./inputs/PTC_MR/ --name 1123_tuned_gmlp_graph_classification_ptc_mr --save_freq 10 --save_dir ./checkpoints --mlflow_root_dir ./mlruns/ --run_name tuned_1123_0_1 --lr 1.18e-4 --beta1 0.9 --beta2 0.9 --hidden_dim 128 --ffn_dim 1024 --n_layers 8 --lr_decay_iters 300 --lr_decay_gamma 0.3 --prob_survival 1. &

wait