python3 gnn/tuning.py \
    --gpu_ids 0 \
    --batch_size 8 \
    --verbose \
    --loss_name bce \
    --network_name gmlp \
    --dataset_name ppi \
    --train_transform_name indegree \
    --val_transform_name indegree \
    --optimizer_name adam \
    --scheduler_name step \
    --n_epochs 1500 \
    --data_dir ./inputs/PPI/ \
    --index_file_dir ./inputs/PPI/10fold_idx/ \
    --name tuning_gmlp_ppi \
    --save_freq 5 \
    --save_dir ./checkpoints \
    --mlflow_root_dir ./mlruns/ \
    --run_name tuning_gmlp_ppi \
    --lr 1e-3 \
    --beta1 0.9 \
    --beta2 0.999 \
    --lr_decay_iters 200 \
    --lr_decay_gamma 0.5
